version: '3'

services:
  kanban_db:
    container_name: kanban_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  kanban_api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: kanban_api
    command: npm run start
    env_file:
      - ./.env
    depends_on:
      - kanban_db
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
