version: '3'

services:
  mysql:
    container_name: kanban_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
