version: '3'

services:
  mysql:
    container_name: kanban_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: kanban_api
    command: npm run start
    env_file:
      - ./.env
    depends_on:
      - mysql
    environment:
      - PORT=${PORT}
    ports:
      - 5000:${PORT}
